// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	inboundorders "github.com/emidioreb/mercado-fresco-lerigophers/internal/inboundOrders"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateInboundOrders provides a mock function with given fields: orderNumber, orderDate, employeeId, productBatchId, warehouseId
func (_m *Repository) CreateInboundOrders(orderNumber string, orderDate string, employeeId int, productBatchId int, warehouseId int) (inboundorders.InboundOrder, error) {
	ret := _m.Called(orderNumber, orderDate, employeeId, productBatchId, warehouseId)

	var r0 inboundorders.InboundOrder
	if rf, ok := ret.Get(0).(func(string, string, int, int, int) inboundorders.InboundOrder); ok {
		r0 = rf(orderNumber, orderDate, employeeId, productBatchId, warehouseId)
	} else {
		r0 = ret.Get(0).(inboundorders.InboundOrder)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int, int, int) error); ok {
		r1 = rf(orderNumber, orderDate, employeeId, productBatchId, warehouseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportInboundOrders provides a mock function with given fields: employeeId
func (_m *Repository) GetReportInboundOrders(employeeId string) ([]inboundorders.ReportInboundOrder, error) {
	ret := _m.Called(employeeId)

	var r0 []inboundorders.ReportInboundOrder
	if rf, ok := ret.Get(0).(func(string) []inboundorders.ReportInboundOrder); ok {
		r0 = rf(employeeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inboundorders.ReportInboundOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(employeeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
