// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	inboundorders "github.com/emidioreb/mercado-fresco-lerigophers/internal/inboundOrders"
	mock "github.com/stretchr/testify/mock"

	web "github.com/emidioreb/mercado-fresco-lerigophers/pkg/web"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateInboundOrders provides a mock function with given fields: orderNumber, orderDate, employeeId, productBatchId, warehouseId
func (_m *Service) CreateInboundOrders(orderNumber string, orderDate string, employeeId int, productBatchId int, warehouseId int) (inboundorders.InboundOrder, web.ResponseCode) {
	ret := _m.Called(orderNumber, orderDate, employeeId, productBatchId, warehouseId)

	var r0 inboundorders.InboundOrder
	if rf, ok := ret.Get(0).(func(string, string, int, int, int) inboundorders.InboundOrder); ok {
		r0 = rf(orderNumber, orderDate, employeeId, productBatchId, warehouseId)
	} else {
		r0 = ret.Get(0).(inboundorders.InboundOrder)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(string, string, int, int, int) web.ResponseCode); ok {
		r1 = rf(orderNumber, orderDate, employeeId, productBatchId, warehouseId)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// GetReportInboundOrders provides a mock function with given fields: employeeId
func (_m *Service) GetReportInboundOrders(employeeId string) ([]inboundorders.ReportInboundOrder, web.ResponseCode) {
	ret := _m.Called(employeeId)

	var r0 []inboundorders.ReportInboundOrder
	if rf, ok := ret.Get(0).(func(string) []inboundorders.ReportInboundOrder); ok {
		r0 = rf(employeeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inboundorders.ReportInboundOrder)
		}
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(string) web.ResponseCode); ok {
		r1 = rf(employeeId)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
