// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	product_records "github.com/emidioreb/mercado-fresco-lerigophers/internal/productRecords"
	web "github.com/emidioreb/mercado-fresco-lerigophers/pkg/web"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateProductRecord provides a mock function with given fields: LastUpdateDate, PurchasePrice, SalePrice, ProductId
func (_m *Service) CreateProductRecord(LastUpdateDate string, PurchasePrice float64, SalePrice float64, ProductId int) (product_records.ProductRecords, web.ResponseCode) {
	ret := _m.Called(LastUpdateDate, PurchasePrice, SalePrice, ProductId)

	var r0 product_records.ProductRecords
	if rf, ok := ret.Get(0).(func(string, float64, float64, int) product_records.ProductRecords); ok {
		r0 = rf(LastUpdateDate, PurchasePrice, SalePrice, ProductId)
	} else {
		r0 = ret.Get(0).(product_records.ProductRecords)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(string, float64, float64, int) web.ResponseCode); ok {
		r1 = rf(LastUpdateDate, PurchasePrice, SalePrice, ProductId)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
