// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	employees "github.com/emidioreb/mercado-fresco-lerigophers/internal/employees"
	mock "github.com/stretchr/testify/mock"

	web "github.com/emidioreb/mercado-fresco-lerigophers/pkg/web"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: cardNumber, firstName, lastName, warehouseId
func (_m *Service) Create(cardNumber string, firstName string, lastName string, warehouseId int) (employees.Employee, web.ResponseCode) {
	ret := _m.Called(cardNumber, firstName, lastName, warehouseId)

	var r0 employees.Employee
	if rf, ok := ret.Get(0).(func(string, string, string, int) employees.Employee); ok {
		r0 = rf(cardNumber, firstName, lastName, warehouseId)
	} else {
		r0 = ret.Get(0).(employees.Employee)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(string, string, string, int) web.ResponseCode); ok {
		r1 = rf(cardNumber, firstName, lastName, warehouseId)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int) web.ResponseCode {
	ret := _m.Called(id)

	var r0 web.ResponseCode
	if rf, ok := ret.Get(0).(func(int) web.ResponseCode); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(web.ResponseCode)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]employees.Employee, web.ResponseCode) {
	ret := _m.Called()

	var r0 []employees.Employee
	if rf, ok := ret.Get(0).(func() []employees.Employee); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employees.Employee)
		}
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func() web.ResponseCode); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *Service) GetOne(id int) (employees.Employee, web.ResponseCode) {
	ret := _m.Called(id)

	var r0 employees.Employee
	if rf, ok := ret.Get(0).(func(int) employees.Employee); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(employees.Employee)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(int) web.ResponseCode); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, requestData
func (_m *Service) Update(id int, requestData map[string]interface{}) (employees.Employee, web.ResponseCode) {
	ret := _m.Called(id, requestData)

	var r0 employees.Employee
	if rf, ok := ret.Get(0).(func(int, map[string]interface{}) employees.Employee); ok {
		r0 = rf(id, requestData)
	} else {
		r0 = ret.Get(0).(employees.Employee)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(int, map[string]interface{}) web.ResponseCode); ok {
		r1 = rf(id, requestData)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
