// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	buyers "github.com/emidioreb/mercado-fresco-lerigophers/internal/buyers"
	mock "github.com/stretchr/testify/mock"

	web "github.com/emidioreb/mercado-fresco-lerigophers/pkg/web"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: cardNumberId, firstName, lastName
func (_m *Service) Create(cardNumberId string, firstName string, lastName string) (buyers.Buyer, web.ResponseCode) {
	ret := _m.Called(cardNumberId, firstName, lastName)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(string, string, string) buyers.Buyer); ok {
		r0 = rf(cardNumberId, firstName, lastName)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(string, string, string) web.ResponseCode); ok {
		r1 = rf(cardNumberId, firstName, lastName)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int) web.ResponseCode {
	ret := _m.Called(id)

	var r0 web.ResponseCode
	if rf, ok := ret.Get(0).(func(int) web.ResponseCode); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(web.ResponseCode)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]buyers.Buyer, web.ResponseCode) {
	ret := _m.Called()

	var r0 []buyers.Buyer
	if rf, ok := ret.Get(0).(func() []buyers.Buyer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]buyers.Buyer)
		}
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func() web.ResponseCode); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *Service) GetOne(id int) (buyers.Buyer, web.ResponseCode) {
	ret := _m.Called(id)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(int) buyers.Buyer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(int) web.ResponseCode); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// GetReportPurchaseOrders provides a mock function with given fields: SectionId
func (_m *Service) GetReportPurchaseOrders(SectionId int) ([]buyers.ReportPurchaseOrders, web.ResponseCode) {
	ret := _m.Called(SectionId)

	var r0 []buyers.ReportPurchaseOrders
	if rf, ok := ret.Get(0).(func(int) []buyers.ReportPurchaseOrders); ok {
		r0 = rf(SectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]buyers.ReportPurchaseOrders)
		}
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(int) web.ResponseCode); ok {
		r1 = rf(SectionId)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, requestData
func (_m *Service) Update(id int, requestData map[string]interface{}) (buyers.Buyer, web.ResponseCode) {
	ret := _m.Called(id, requestData)

	var r0 buyers.Buyer
	if rf, ok := ret.Get(0).(func(int, map[string]interface{}) buyers.Buyer); ok {
		r0 = rf(id, requestData)
	} else {
		r0 = ret.Get(0).(buyers.Buyer)
	}

	var r1 web.ResponseCode
	if rf, ok := ret.Get(1).(func(int, map[string]interface{}) web.ResponseCode); ok {
		r1 = rf(id, requestData)
	} else {
		r1 = ret.Get(1).(web.ResponseCode)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
