// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	carriers "github.com/emidioreb/mercado-fresco-lerigophers/internal/carriers"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: cid, companyName, address, telephone, localityId
func (_m *Repository) Create(cid string, companyName string, address string, telephone string, localityId string) (carriers.Carry, error) {
	ret := _m.Called(cid, companyName, address, telephone, localityId)

	var r0 carriers.Carry
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) carriers.Carry); ok {
		r0 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r0 = ret.Get(0).(carriers.Carry)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(cid, companyName, address, telephone, localityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: cid
func (_m *Repository) GetOne(cid string) (carriers.Carry, error) {
	ret := _m.Called(cid)

	var r0 carriers.Carry
	if rf, ok := ret.Get(0).(func(string) carriers.Carry); ok {
		r0 = rf(cid)
	} else {
		r0 = ret.Get(0).(carriers.Carry)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
