// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	time "time"

	purchase_orders "github.com/emidioreb/mercado-fresco-lerigophers/internal/purchaseOrders"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreatePurchaseOrders provides a mock function with given fields: OrderNumber, OrderDate, TrackingCode, BuyerId, ProductRecordId, OrderStatusId
func (_m *Repository) CreatePurchaseOrders(OrderNumber string, OrderDate time.Time, TrackingCode string, BuyerId int, ProductRecordId int, OrderStatusId int) (purchase_orders.PurchaseOrders, error) {
	ret := _m.Called(OrderNumber, OrderDate, TrackingCode, BuyerId, ProductRecordId, OrderStatusId)

	var r0 purchase_orders.PurchaseOrders
	if rf, ok := ret.Get(0).(func(string, time.Time, string, int, int, int) purchase_orders.PurchaseOrders); ok {
		r0 = rf(OrderNumber, OrderDate, TrackingCode, BuyerId, ProductRecordId, OrderStatusId)
	} else {
		r0 = ret.Get(0).(purchase_orders.PurchaseOrders)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time, string, int, int, int) error); ok {
		r1 = rf(OrderNumber, OrderDate, TrackingCode, BuyerId, ProductRecordId, OrderStatusId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
